-- CRIAR BD 
CREATE DATABASE GREENHOUSE;

-- definir bd como padrão/ utilizável
USE GREENHOUSE;

-- CRIAR TABELA/ENTIDADE
CREATE TABLE `PLANTS` (
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT NOT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL 
		DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY `PK_PLANTS` (`PLANT_NAME`)
);

-- VISUALIZAR TODAS AS OCORR^^ENCIAS EM PLANTS
-- LISTAR TODOS OS REGISTROS DE DADOS

SELECT * FROM PLANTS;

SELECT PLANT_NAME, SENSOR_VALUE, SENSOR_EVENT FROM PLANTS;
 
-- INSERIR DADOS NA TABELA/ENTIDADE PLANTS
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES('Rosa', '0.2319');

-- INSERIR MÚLTIPLOS REGISTROS DE UMA VEZ
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE) 
VALUES
	('Cactus', 0.2411),
    ('Girassol','0.3112'),
    ('Orquídea', 0.4102),
    ('Lirio', 0.5566);
    
-- CONSULTA APLICANDO FILTROS
SELECT *
FROM PLANTS
WHERE PLANT_NAME = 'Cactus';

-- FILTROS COM OPERADORES AND OR XOR ETC
SELECT *
FROM PLANTS
WHERE PLANT_NAME <> 'CANNABIS'
AND SENSOR_VALUE < 0.5566
AND SENSOR_VALUE > 0.2411;